theme: jekyll-theme-minimal

title: MPI with Docker and Singularity

#navbar-links:
#  - Home: "/README.md"
#  - License: "/LICENSE.md"
#  - MPICH: "https://www.mpich.org/"

relative_links:
  enabled: true
  collections: true
include:
  - _data
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - MISC.md
  - ABOUT_US.md

sidebar:
  nav: "docs"

plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
