theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - MISC.md
  - ABOUT_US.md

docs_list_title: TestMPI
docs:
  - title: About us
    url: ABOUT_US.md
  
  - title: License
    url: LICENSE.md

  - title: Miscellaneous
    url: MISC.md